name: TheBizdom
title: TheBizdom | BIZ of the wisDOM
description: We are in the BIZness of spreading wisDOM.
tags:
  - Indian Business History
  - Modern India
  - Data Story
  - Startups
  - Fintech
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Newsletter
    url: /newsletter

